version: "3"
services:
  flake8-bugbear_sample:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /project
    volumes:
      - .:/project
      - ${USERPROFILE-~}/.ssh:/home/vscode/.ssh
    image: flake8-bugbear_sample-image
    container_name: flake8-bugbear_sample-container
    tty: true
